require "bundler/gem_tasks"
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'lib/lucie'
  t.libs << 'test'
  t.test_files = FileList['test/*/*_test.rb']
  t.verbose = false
  t.warning = true
end
task :default => :test