require "bundler/gem_tasks"
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'lib'
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = false
  t.warning = true
end
task :default => :test

if !ENV["TRAVIS"]
  require 'rdoc/task'
  RDoc::Task.new :doc do |rdoc|
    rdoc.rdoc_dir = '../doc'
    rdoc.options << '-f' << 'sdoc'
    rdoc.rdoc_files.include("lib/*.rb")
  end
end