require "bundler/gem_tasks"
require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'app'
  t.libs << 'app/controllers'
  t.libs << 'spec'
  t.test_files = FileList['spec/*/*_spec.rb']
  t.verbose = false
  t.warning = true if ENV["TRAVIS"]
end
task :default => :test

if !ENV["TRAVIS"]
  require 'rdoc/task'
  RDoc::Task.new :doc do |rdoc|
    rdoc.rdoc_dir = '../doc'
    rdoc.options << '-f' << 'sdoc'
    rdoc.rdoc_files.include("lib/*.rb")
  end
end
