require "bundler/gem_tasks"
require 'rake/testtask'

if !ENV["TRAVIS"]
  require 'rdoc/task'
end

Rake::TestTask.new do |t|
  t.libs << 'lib/lucie'
  t.libs << 'test'
  t.test_files = FileList['test/*/*_test.rb']
  t.verbose = false
  t.warning = true if ENV["TRAVIS"]
end
task :default => :test

RDoc::Task.new :doc do |rdoc|
  rdoc.rdoc_files.include("lib/*.rb")
end